CREATE TABLE CadastroCritico2 (
    ID_CRITICO VARCHAR (30) NOT NULL ,
	NOME VARCHAR (30) NOT NULL ,
	SENHA VARCHAR (30) NOT NULL,
	DATANASCIMENTO VARCHAR (20)  NOT NULL,
	EMAIL VARCHAR (30) NOT NULL

);

SELECT * FROM CadastroCritico2  