CREATE TABLE Compras (
    NOMEFILME  VARCHAR(30) NOT NULL,
    GENEROFILME VARCHAR(30) NOT NULL
);
SELECT * FROM Compras; 
SELECT COUNT (*) FROM Compras AS cr WHERE cr.generofilme LIKE 'infantil' ;
SELECT COUNT(*) FROM Compras;
ALTER TABLE Compras ADD SEMANA VARCHAR(30) NULL

