CREATE TABLE Critico (
    NOME  VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    SENHA VARCHAR(30) NOT NULL,
    DATADENASCIMENTO VARCHAR(30) NOT NULL,
    IDENTIFICADOR  VARCHAR(30) NOT NULL

);
SELECT * FROM Critico; 
ALTER TABLE Critico ADD SEMANA VARCHAR(30) NULL

