CREATE TABLE Cadastro (
    NOME  VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    SENHA VARCHAR(30) NOT NULL,
    DATADENASCIMENTO VARCHAR(30) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    GENERO  VARCHAR(30) NOT NULL

);
SELECT * FROM Cadastro; 
SELECT COUNT(*) FROM Cadastro;
ALTER TABLE Cadastro ADD SEMANA VARCHAR(30) NULL



